Desafio 5. itens A e B
igorgavilon/HelpperOrigins pull request #1
Opened 2021-11-11 02:10 UTC by igorgavilon

resolução do exercício 5 A e B

no exercício 5B tentou-se utilizar a importação da classe de outro arquivo mas o browser não aceita trabalhar com módulos e os import e export. ficou tudo num mesmo arquivo, desafio5b.ts: a definição da classe e seu uso!

2021-11-11 22:17 UTC, matheus-yudi-helpper requested changes

2021-11-11 22:17 UTC, matheus-yudi-helpper commented on sprint2/desafio5/desafio5a/AnalisaPalavra.ts
> + * possui um étodo estático contaVogais
Corrigir o comentário.

2021-11-11 22:17 UTC, matheus-yudi-helpper commented on sprint2/desafio5/desafio5a/AnalisaPalavra.ts
> +    static contaVogais(palavra: string): number {
Sempre que possível, procure colocar o nível de acesso do método (public, protected, private).

2021-11-11 22:17 UTC, matheus-yudi-helpper commented on sprint2/desafio5/desafio5a/AnalisaPalavra.ts
> +        return (palavra.match(/[aeiou]/gi) || []).length;
Se a vogal conter acentos, esta regex irá considerar? Tenta abrangir também essa possibilidade.

2021-11-11 22:17 UTC, matheus-yudi-helpper commented on sprint2/desafio5/desafio5b/desafio5b.ts
> + * possui um étodo estático contaVogais
Corrigir o comentário.

2021-11-11 22:17 UTC, matheus-yudi-helpper commented on sprint2/desafio5/desafio5b/desafio5b.ts
> +    static contaVogais(palavra: string): number {
Colocar o nível de acesso.

2021-11-11 22:17 UTC, matheus-yudi-helpper commented on sprint2/desafio5/desafio5b/desafio5b.ts
> +        return (palavra.match(/[aeiou]/gi) || []).length;
Mesmo caso da classe do desafio5a.

2021-11-12 00:50 UTC, ErickSasaki approved these changes

2021-11-12 00:50 UTC, ErickSasaki commented on sprint2/desafio5/desafio5a/AnalisaPalavra.ts
> +        return (palavra.match(/[aeiouáàãâäéèêëíìîïóòõôöúùûü]/gi) || []).length;
rapaz

2021-11-20 15:03 UTC, merged